### ISSUE TITLE
怎么默认设置成内网访问

### ISSUE THREAD

**Issue by hou6807628** [nuanxinqing123/HomeNavigation#4]
我一般是在局域网内用，所以外网一般用的次数不多，希望了解一下怎么设置成默认内网访问，谢谢！

**Comment by nuanxinqing123** [comment]
指的是从内网访问IP地址，还是默认进去之后显示内网的项目？

**Comment by hou6807628** [comment]
就是我点击图标的时候，它默认打开的是内网的地址，ip:端口

**Comment by nuanxinqing123** [comment]
好的，明白了。我会在1.7版本里面新增此功能，请多关注仓库的更新动态
