### ISSUE TITLE
nas上使用docker启动不了

### ISSUE THREAD

**Issue by codesensi** [nuanxinqing123/HomeNavigation#9]
以下是配置截图
![c85c39ae287319776e30816d95591c9](https://user-images.githubusercontent.com/66196408/187208417-d80a40a8-1974-4637-b497-801556cb1dcc.jpg)
![6ce4b9ee34640f21b0ce242517af230](https://user-images.githubusercontent.com/66196408/187208430-a6b48fe5-829d-49ba-babd-dfa6fe33873f.jpg)
![60d7443e7bebbdf80eca36816a74311](https://user-images.githubusercontent.com/66196408/187208438-c6e19584-b6f6-4968-8893-f135a7d39b58.jpg)
以下是启动报错的日志截图
![1617e20a1e3b2dd9858957e1d8b6a0b](https://user-images.githubusercontent.com/66196408/187208493-849b3015-b8b2-467b-a603-d3f2a095ddc7.jpg)
想请问一下作者大大，是不是我哪里做得有问题

**Comment by lemonsnack** [comment]
解决了吗？

**Comment by codesensi** [comment]
> 解决了吗？

太菜了，没解决，暂时没用这个了
